%stare(alb,alb,alb,spatiu,negru,negru,negru)
initial(stare(a,a,a,s,n,n,n)).
final(stare(n,n,n,s,a,a,a)).

mutare(stare(s,n,X,Y,Z,T,V),stare(n,s,X,Y,Z,T,V)).
mutare(stare(X,s,n,Y,Z,T,V),stare(X,n,s,Y,Z,T,V)).
mutare(stare(X,Y,s,n,Z,T,V),stare(X,Y,n,s,Z,T,V)).
mutare(stare(X,Y,Z,s,n,T,V),stare(X,Y,Z,n,s,T,V)).
mutare(stare(X,Y,Z,T,s,n,V),stare(X,Y,Z,T,n,s,V)).
mutare(stare(X,Y,Z,T,V,s,n),stare(X,Y,Z,T,V,n,s)).
mutare(stare(X,Y,Z,T,V,a,s),stare(X,Y,Z,T,V,s,a)).
mutare(stare(X,Y,Z,T,a,s,V),stare(X,Y,Z,T,s,a,V)).
mutare(stare(X,Y,Z,a,s,T,V),stare(X,Y,Z,s,a,T,V)).
mutare(stare(X,Y,a,s,Z,T,V),stare(X,Y,s,a,Z,T,V)).
mutare(stare(X,a,s,Y,Z,T,V),stare(X,s,a,Y,Z,T,V)).
mutare(stare(a,s,X,Y,Z,T,V),stare(s,a,X,Y,Z,T,V)).
mutare(stare(a,n,s,X,Y,Z,T),stare(s,n,a,X,Y,Z,T)).
mutare(stare(X,a,n,s,Y,Z,T),stare(X,s,n,a,Y,Z,T)).
mutare(stare(X,Y,a,n,s,Z,T),stare(X,Y,s,n,a,Z,T)).
mutare(stare(X,Y,Z,a,n,s,T),stare(X,Y,Z,s,n,a,T)).
mutare(stare(X,Y,Z,T,a,n,s),stare(X,Y,Z,T,s,n,a)).
mutare(stare(X,Y,Z,T,s,a,n),stare(X,Y,Z,T,n,a,s)).
mutare(stare(Y,Z,T,s,a,n,X),stare(Y,Z,T,n,a,s,X)).
mutare(stare(Z,T,s,a,n,X,Y),stare(Z,T,n,a,s,X,Y)).
mutare(stare(T,s,a,n,X,Y,Z),stare(T,n,a,s,X,Y,Z)).
mutare(stare(s,a,n,X,Y,Z,T),stare(n,a,s,X,Y,Z,T)).

solution(Sol):-initial(Stare),bkt(Stare,[],Sol).
bkt(Stare,Drum,[Stare|Drum]):-final(Stare).
bkt(Stare,Drum,Solutie):-mutare(Stare,SNoua),not(member(SNoua,[Stare|Drum])),
    bkt(SNoua,[Stare|Drum],Solutie).
pion:-solution(Sol),display1(Sol).
display1([]):-nl.
display1([X|T]):-display1(T),nl,write(X).
